### ISSUE TITLE
Type formats

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1050]
- `TxValTag` and `IsFee` tag - should they keep their names, or just be booleans?
- Should we have the IsFee field for script inputs, but not actually allow them to be marked as fees?
-  As a general heuristic, should types that are different for the script and public key cases, such as transaction inputs, be expressed as 
`Common_data_for_both \times Maybe ScriptStuff \times Maybe PKStuff`

or is it better to go with a disjoint union `TxIn_for_scripts \disjointunion TxIn_for_PK`

**Comment by JaredCorduan** [comment]
labeling the booleans seems nice for readability. but maybe instead of three new types `IsThing`, `Yup`, and `Nope`, with `IsThing=Yup U Nope` and `predicates x in Yup`, we could write `IsThing = {Yup, Nope}` with `predicate x = Yup`.

In terms of keeping the changes to the existing shelley spec smaller and easier to understand, I think it's easier to add stuff to the existing `TxIn`s and just say to swap the new one out for the old one. I just say that since all the case distinctions seem to then cascade out to all the other types...
