### ISSUE TITLE
Optional redeemers for all (and maybe optional DataValues too)

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1166]
Since it seems that allowing forging scripts to have redeemers will not be harmful and possibly useful even, would it make sense to allow all Plutus scripts to have redeemers? This would then include 
- forging scripts
- certificate scripts
- reward withdrawal scripts
- output locking scripts (which do already have non-optional redeemers)

Which brings me to the next point of this issue: should *all* data-values and redeemers be optional? 

This would likely work best by storing them in a separate data structure indexed by the type of thing that they validate (i.e. for forging - the `CurrencyID`, for certificates - ???, for rewards - the reward address, and for outputs - `(txid, ix)`). Does this sound like a good idea? What are the possible dangers here?

**Comment by polinavino** [comment]
DataValues are still only for output locking. 

Also, what is the best way to pass these arguments to the interpreter? Currently, they are passed as a list in the spec, which is always either `[pendingTx]` or `[pendingTx, dataValue, redeemer]`. It will be more confusing when we can have lists of two things and it is not clear whether the second is a data value or redeemer.

**Comment by michaelpj** [comment]
IMO there are three issues here, I think we should split this issue up.

1) Should all scripts have redeemers?

My inclination is yes. They're useful, and it doesn't cost us much, except adding more stuff into the transaction (which may be bad).

2) How should we represent the redeemers for scripts?

We can always put them next to the place where we list the script, i.e.
- On inputs for normal validators
- In the list of forging scripts for MPSs, etc.

However, it might be nice to keep them on the side (perhaps along with the cost information etc.). This would require some data structures with appropriate indexes to look up the redeemers etc.

I don't think we should ever use the script hash as the index. It's obviously not okay for normal validators, since the same validator can appear multiple times in the same transaction but with different redeemers. It's perhaps okay currently for the other uses of scripts, but I'm concerned that a similar situation could arise if we change the spec and we wouldn't notice.

I think we should instead use an index that picks out the location of that script in the transaction. Indices into lists for things that are in ordered lists would work well, e.g. the index of the transaction input in the list of inputs, the index of the MPS in the list of MPSs, etc. (This does require a different data structure for each of the different types of script, but I think that's maybe a good thing.)

3) Should we allow redeeemers/data values to be optional and what should the ledger do if they are omitted?

I think optional redeemers/data values would be nice and would save us some space. However, I think the ledger should be responsible for inserting a default value as soon as possible, so everything else can act as though they're always present (this is pretty standard programming practice).

e.g. you have `getRedeemerAndData :: ScriptTxIn -> (Data, Data)` or whatever, and it has to put in a unit value if one of them is missing.

Otherwise we complicate everything downstream. I think it's much better if e.g. the interpreter just gets a list of arguments with the correct number and type of arguments.

**Comment by polinavino** [comment]
> I don't think we should ever use the script hash as the index. 

This is *only* done for forging scripts. CurrencyID (the hash of the script) is the only thing by which to identify them. The other redeemers are indexed by the corresponding relevant thing (withdrawal address, input reference, etc.). This can all be done in a single data structure (which must necessarily be inside the body of the transaction):
`CurItem |-> DataHash`

Once the hash of the redeemer (or even the `DataValue`) is looked up in this structure, the full corresponding `Data` term is looked up in the `UnsignedData` portion of the transaction. `UnsignedData` is the non-body part of the transaction, where the metadata, signatures, tags, and full `Data` and `Script` things go. 

This setup favours heavily making the `DataValue` arguments to output-locking Plutus scripts optional also, since all the infrastructure is set up already.

> I think the ledger should be responsible for inserting a default value as soon as possible, so everything else can act as though they're always present

Indeed.

**Comment by michaelpj** [comment]
> This is only done for forging scripts. CurrencyID (the hash of the script) is the only thing by which to identify them.

I thought we were having a list of the MPSs called `forgeScripts`, right? So there is something to identify them: their index in that list.

> This can all be done in a single data structure (which must necessarily be inside the body of the transaction): CurItem |-> DataHash

But the type of `CurItem` is different for every kind of script. Are you intending `CurItem` there to be a big sum type? (Also I don't think it's *necessarily* the case that the thing we use to pick out the script for this purpose should be the same as the "current item" we put in the `PendingTx`, although it's plausible.)
