### ISSUE TITLE
How should we handle large, segregated bits of data?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-ledger-specs#1201]
In transactions we have a number of large objects related to validation, but which aren't required for block replay. So we'd like to avoid including them in the transaction body.

This includes at least.
- Transaction metadata
- Scripts
- Redeemers
- Data values

(Reminder: a data value is the `Data` object attached to script transaction outputs. Other things may be of (representational) type `Data`, in particular redeemers (and probably transaction metadata values) will also be of (representational) type `Data`.)

We've talked about handling these in a couple of different ways, which I wanted to write down so we could maybe take a consistent stance.

# Approach 1: indirection via hashes

The approach here is fairly consistent and simple: wherever we have a large object we don't want to include inline, we replace it with its hash. Then on the side we have a map from hashes to the full value (henceforth a "hash lookup map"), one for each type of thing.

For example, this would mean:
- Validator scripts and redeemers on inputs are replaced by hashes.
- Transaction metadata is a map from `uints` to data hashes.
- We have (at least) two hash lookup maps outside the transaction body:
    - One for scripts
        - This includes all scripts: validators, monetary policy scripts, scripts for rewards etc.
    - One for everything of (representational) type `Data`
        - This includes redeemers, data values, and the values of the metadata map

One question with this approach is whether we should have *one* hash lookup map for all the different kinds of scripts, or one for each of validator scripts, monetary policy scripts, etc. (and similarly we could have a single map for all things of type `Data`, or one for each of transaction metadata values, redeemers, data values etc.).

Code sketch:
```
data TxInput = .. | ScriptTxInput { ..., txInputRedeemer :: DataHash, ... }
data Tx = Tx {
    txBody :: TxBody,
    ...
    txDataHashLookupMap :: Map DataHash Data
}
```

# Approach 2: indirection via separate structures

Approach 1 requires us to put lots of hashes in the transaction body, making it bigger. An alternative is to bundle all the extra information together into a separate structure, and then include only a hash of *that* in the body itself.

For example, we could put the transaction metadata map outside the body, and include only a hash of the entire map in the body.

This requires some changes to how we represent things. For example, rather than putting redeemers inline as part of transaction inputs, we would instead need e.g. a map from transaction input indices to redeemers. We could then put *that* map outside the transaction body, and include a hash of it in the body. In that respect this is a less "obvious" approach than Approach 1, since we need to change the structure of the transaction, instead of just replacing objects by hashes wherever they occur.

On the plus side, we essentially don't need any hash lookup maps if we adopt this approach: we can just put the full value in the separate structures, since they're already outside the transaction body.

For example, we can just include the full transaction metadata value in the map, rather than a hash. And we could map transaction input indices directly to redeemers, rather than to hashes.

Code sketch:
```
data TxInput = ... -- no special case for script inputs
data TxBody = TxBody {
    ...
    txRedeemersHash :: Hash
}
data Tx = Tx {
    txBody :: TxBody,
    ...
    txRedeemers :: Map Integer Redeemer -- Redeemer is representationally equivalent to Data
}
```

-----

Overall, Approach 1 is perhaps easier, but Approach 2 minimizes the size of the transaction body.

I don't have strong feelings, but I think we should pick a policy and stick to it consistently.

**Comment by JaredCorduan** [comment]
thank you for writing this up! now I understand how this effects the redeemers. I also do not have a strong opinion.

**Comment by polinavino** [comment]
Scripts:
Since anything locked by a script necessarily requires a transaction to have that script, and its hash to be computed, I think having all scripts (MSig, Plutus, etc), in a set outside the transaction body (rather than a hash-indexed map), with a hash of this whole set inside the body, would probably make the most sense to me.

Data:
I think approach 2 makes sense. We can, I would say, jam all three types of things (redeemers, data-values, metadata) into a single `Map CurItem Data` lookup map, where `CurItem` is a big sum type that is one of these things:
- index for redeemer look-up for the transaction output (for script UTxO entry spending)
- index for data value look-up for the transaction output (also for script UTxO entry spending)
- currencyID (for forging scripts)
- certificates 
- withdrawals

Either that ^^ or separate these things into distinct maps (`Map RedeemerIx Data`, `Map DataValueIx Data`, etc). I am rather opposed to having an index `Ix` to index all of these things, I think it would make everything much more confusing

**Comment by polinavino** [comment]
Also thank you @michaelpj for writing all this up =D

**Comment by michaelpj** [comment]
> Since anything locked by a script necessarily requires a transaction to have that script, and its hash to be computed, I think having all scripts (MSig, Plutus, etc), in a set outside the transaction body (rather than a hash-indexed map), with a hash of this whole set inside the body, would probably make the most sense to me.

I *think* you're advocating for Approach 2 here, but if so we can't just have a set, they need to be indexed by something, otherwise we don't know what validator goes on an input, etc.

> I am rather opposed to having an index Ix to index all of these things, I think it would make everything much more confusing.

I'm not sure what you're referring to here - isn't this just what you were suggesting with `CurItem`?

**Comment by polinavino** [comment]
> we can't just have a set, they need to be indexed by something, otherwise we don't know what validator goes on an input, etc.

I am saying that scripts dont need to be indexed by anything. Their hashes have to be computed and checked agains their indeces (which should be their hashes). Which is an extra unnecessary check if we get rid of the hashes as indeces. We do know what validator goes on what input as we look through the set and compute the hash of each

> I'm not sure what you're referring to here - isn't this just what you were suggesting with CurItem?

It is what I am suggesting - kind of. I am against doing everything using `Ix` (for example, instead of currency ID). But I am not sure if it is better to have several maps like
`Map CurrencyId Data`
`Map RedeemerIx Data`
...

or just one, with a sum-type index `CurItem` which can be any of those things

**Comment by michaelpj** [comment]
> I am saying that scripts dont need to be indexed by anything. Their hashes have to be computed and checked agains their indeces (which should be their hashes). Which is an extra unnecessary check we wont have to do if we get rid of the hashes as indeces.

I don't understand what you're saying here. Perhaps we're talking about different things when we say "index"? I have been using it to mean:
- In the case of transaction inputs, their index in the list of transaction inputs
- In the case of other things, whatever identifies them (i.e. `CurItem`)

> We do know what validator goes on what input as we look through the set and compute the hash of each

This is only the case if we put the hash on the transaction input. Approach 2 suggests *not* doing that: exactly like the example with redeemers. So are you in fact suggesting Approach 1?

**Comment by polinavino** [comment]
> This is only the case if we put the hash on the transaction input. Approach 2 suggests not doing that: exactly like the example with redeemers. So are you in fact suggesting Approach 1?

The hashes of the validators are always known because they are either in the UTxO entries, are the currency ID's in the `Value` type for forging, the reward addresses, or in the certificate. So we have to find the script in the set that matches the validator hash in the thing we are trying to validate

**Comment by michaelpj** [comment]
> The hashes of the validators are always known because they are either in the UTxO entries, are the currency ID's in the Value type for forging, the reward addresses, or in the certificate. We are not getting rid of them in those places - i dont think this would make sense.

Getting rid of them in those places is *precisely* what Approach 2 suggests (have another read!). Instead we would have a mapping from some suitable index for each of these things (`CurItem` would do) to the script.

You're suggesting a variant of Approach 1 (which is fine, it just sounded like you were in favour of Approach 2).

----

Summary of some discussion on Slack:

If we did Approach 1, we don't need to use hash lookup maps. We could instead just use a set, and compute the mapping in-memory during validation. We already have to compute the hashes during validation to check them, so we don't even spend more time this way.

One place the hash lookup map *is* useful is in the Plutus representation of transactions (`PendingTx`). It's nice to be able to look up e.g. a data value by hash without having to actually hash all the values. Instead, we can rely on the node having checked that all the hashes are correct, and just do a map lookup.

This isn't too bad: we can always use that representation for `PendingTx` but not the real `Tx`.

(I don't remember where I got the hash-lookup map idea from - I thought I got it from the ledger team, but who knows.)

**Comment by polinavino** [comment]
For scripts, yes - closer to Approach 1, but without hash-indexes. Sounds like it is ok for `PendingTx` too.

For `Data` things, closer to Approach 2, indexed by whatever thing necessary (which can anyway be a hash, like for Currency ID)

**Comment by michaelpj** [comment]
I'm keen to have a single approach for everything. I don't see that scripts are any different from data, they're both just parts of data structures that we can keep in one place or another. The arguments that apply to one should apply to the other.

What's the argument for doing them differently?

**Comment by polinavino** [comment]
Scripts are mandatory and have always had one layer of "indirection", so to say. The thing that needs a script to be run always has the hash of that script - changing this would cause problems (like changes to address structure)

Data is optional, and because of this, we have been considering two layers of indirection. The 
`Map Index DataHash` or `Map CurItem DataHash` (for metadata and redeemers, respectively), and then on top of that, a `Map DataHash Data`. I thought this is what you were avoiding with approach 2, ie
Only have the `Map Index (or CurItem) Data` directly, with a hash of this in the body.

**Comment by michaelpj** [comment]
> The thing that needs a script to be run always has the hash of that script - changing this would cause problems (like changes to address structure)

That's true - addresses do have the validator hash in them! I agree we shouldn't change that.

I would say the Approach 2 solution to that is: leave the hash in there, but still index the scripts by something. Two reasons:
1. Consistency
2. This will work nicely if we have places which use scripts but we *don't* fundamentally need to have the hash in the body. I'm not sure whether that applies to any of our script uses at the moment, but it definitely could.

> Data is optional, and because of this, we have been considering two layers of indirection. 

I *think* the optionality is a red herring. 

> I thought this is what you were avoiding with approach 2

I agree with what you wrote there.

**Comment by polinavino** [comment]
> I would say the Approach 2 solution to that is: leave the hash in there, but still index the scripts by something. 

If they're indexed by something that makes sense and is smaller than a hash, that works. But, as you pointed out, the `Map ScriptHash Script` map will be built locally by each node as part of following the ledger rules (this is in order to avoid computing the hash of a script more than once). I think it would make sense to just use this map.

**Comment by michaelpj** [comment]
> If they're indexed by something that makes sense and is smaller than a hash, that works. But, as you pointed out, the Map ScriptHash Script map will be built locally by each node as part of following the ledger rules (this is in order to avoid computing the hash of a script more than once). I think it would make sense to just use this map.

I agree that the hash lookup map is not the right thing, so I don't think we want to revive it in Approach 2!

I think we could index by something smaller than the hash: essentially the `CurItem`:
- Index in the list of transaction inputs for normal validators
- Might actually need to be the script hash for MPSs
- index in the list of withdrawals for reward locking scripts
etc.

**Comment by JaredCorduan** [comment]
How about this variant of Approach 2:

On the wire we put a set of `Data` values outside the body, and a hash of this set inside the body. When we deserialize the transaction, we use the set of data to construct a map from data hashes to data (in addition to checking the hash in the body).

**Comment by michaelpj** [comment]
> When we deserialize the transaction, we use the set of data to construct a map from data hashes to data (in addition to checking the hash in the body).

If we use Approach 2 we don't need the map of data hashes to data.

(We may want to construct this when we construct the `PendingTx`, but that's a separate question.)

**Comment by JaredCorduan** [comment]
> If we use Approach 2 we don't need the map of data hashes to data.

Since the downside of Approach 2 is:

> This requires some changes to how we represent things. For example, rather than putting redeemers inline as part of transaction inputs, we would instead need e.g. a map from transaction input indices to redeemers. 

Doesn't the map of data hashes to data would give you back the representation you wanted?

**Comment by michaelpj** [comment]
> Doesn't the map of data hashes to data would give you back the representation you wanted?

No, because the point of Approach 2 is taking those bits of data out of the data structures. What you're suggesting won't put them back again! Maybe the code examples that I posted would make it clearer.

The hash lookup map vs set is a red herring. It just makes Approach 1 slightly more compact and is an aside to the main thing I wanted to talk about.

**Comment by polinavino** [comment]
> I think we could index by something smaller than the hash: essentially the CurItem

You are talking about scripts here, right? Scripts never need to be indexed by anything because:

- their hashes always have to be computed as part of transaction validation, so we are not wasting time or space by making a local `ScriptHash |-> Script` map (not included in original transaction data), which we then use to look them up
- in ledger or transaction data, we cannot get rid of hashes as identifiers for some things that need the corresponding script to be run (a script that hashes to this value), namely, currency ID, certificate data, reward, or UTxO entry addresses

I would say this is a good enough argument to keep scripts as a set.

**Comment by polinavino** [comment]
To summarize what we talked about on a call earlier, (a full formal/executable spec description to follow, along with a beautiful amoeba-inspired diagram by Alex):

```
block =
  [ header
  , transaction_bodies         : [* transaction_body]
  , transaction_witness_sets   : [* transaction_witness_set]
  , transaction_metadata_set   : { * uint => transaction_metadata }
  ]
transaction_witness_set = 
  { ?0 => [* pubkey_witness]
  , ?2 => [* script]
  , ?3 => {* rev_ptr => redeemer}
  , ?4 => [* data_value_inputs]
  , ?5 => [* data_value_outputs]
  }
rev_ptr = [ type, offset ]
type = 
   0 ; utxo
 / 1 ; forging
 / 2 ; etcetera
 / 3 ; withdrawals
 / 4 ; rocks
 / 5 ; pepper
 / 6 ; bicycles
 / 7 ; intangibles
offset = uint ; 
```

There are 2 flavours of things related to witnessing that must live outside the transaction body (this does not include metadata, as it's not used for witnessing), 
1. those that are referenced directly inside the transaction or the UTxO, i.e.
- pubkey witnesses - we know which keys must sign what because of whose key hash is in the UTxO entry output being spent)
- scripts (both msig and plutus), because the hash of the script that needs to be run is always in the thing being validated (forging has currency IDs, outputs and rewards have addresses, etc)
- data values (these have their hashes in either the Tx outputs, or UTxO outputs)

2. those that must have an explicit association imposed on them in order to find the right specific thing for witnessing, i.e
- redeemers (no hashes of these hanging around already)

The things in the first group are stored in lists (a list of each type of thing: scripts, data, etc.)

The things in the second group are stored as a map, with keys `rev_pointer`. This pointer is a pair of the type of thing that needs this redeemer (forging, outputs, etc.) and an index indicating the position of thing in the bunch of these things. For example, if in the `forge` field we have
`currencyID1 |-> tokens`
`currencyID2 |-> tokens`
in the `{* rev_ptr => redeemer}` map we would have
`[(forge 1, redeemer1), (forge 2, redeemer2)]`

**Comment by polinavino** [comment]
One thing I am still confused about is this "offset" notion. How would I represent it in the formal spec? Explicitly, like for outputs (`Ix |-> TxOut`), so the forge field would be 
`Ix |-> Value`

How would this work for things already in a list, like certificates? do they need indexes too now?

Or implicitly somehow? like have an abstract map `DCert -> Ix` that gets the position of the thing in the bunch of things?

**Comment by michaelpj** [comment]
Thanks, that's a nice clear explanation! I'm happy with something like that.

Some comments:
- We could probably merge `data_value_inputs` and `data_value_outputs`. Or not, I'm not sure if it matters.
- AFAIK we're still planning to have an explicit list of forging scripts (name TBD) in the transaction, right? So it would make sense to me for the "offset" for the MPS redeemers to be the index in that list, rather than trying to decompose the `Value` in `forge`.
- The `rev_ptr` type to my mind maybe makes some assumptions (e.g. that these things don't occur inside nested structures, where you might need more offsets). I'd be inclined to have
    - A "pointer" type per type of thing
    - A redeemer map per kind of thing

Maybe that's too many witness buckets? But if we want to differentiate e.g. `data_value_inputs` and `data_value_outputs` then we're already being pretty fine-grained about how we divide things up. I think we should be consistent: either lump together all the things of the same type, or differentiate them all by what they're for.

**Comment by polinavino** [comment]
`data_value_inputs` and `data_value_outputs` together makes sense. I am not totally sure what you mean by

> A "pointer" type per type of thing
> A redeemer map per kind of thing

Can you explain more/give an example?

The upside of my original thought of using `CurItem` as a (non-reverse) pointer from the thing that needs the redeemer to the full redeemer is that it is very clear what is going on, how things are related to each other, and how to formalize/implement it. The downside is that current item contains large, transaction-bulking hashes and things. I think a decent compromise would be, instead of `Ix |-> Value` (since I have a feeling the index has to be made explicit anyways), use 

`Value |-> Ix`,

with `ix = 0` those things that dont have redeemers, for example. Then, for  each `value |-> ix`, look for the corresponding `(forge ix)`

**Comment by michaelpj** [comment]
> Can you explain more/give an example?

Yep.

```
transaction_witness_set = 
  { 
  ...
  , ?3 => {* input_pointer => redeemer} # redeemers for transaction inputs
  , ?4 => {* forge_pointer => redeemer} # redeemers for MPSs
  ...
  }
input_pointer = uint # index of input in list of inputs
forge_pointer = uint # index of MPS in list of MPSs - see below for more explanation
```

Why have all these different `X_pointer` types? a) it cleanly separates the maps for different types of things, and b) it's forwards-compatible with anything that needs a more complex kind of pointer. And it probably doesn't actually take up much more space to have multiple maps.

If we did this, though, I think we should *not* separate `data_value_inputs` and `data_value_outputs`, so that we're applying reasoning a) consistently.

> I think a decent compromise would be, instead of Ix |-> Value (since I have a feeling the index has to be made explicit anyways), use
 > Value |-> Ix,
> with ix = 0 those things that dont have redeemers, for example. Then, for each value |-> ix, look for the corresponding (forge ix)

I'm not sure I follow. But I think we can do it much more simply than that.

Remember that in the discussion about separate MPSs we agreed we were going to have an explicit field separate from `forge` which lists the MPSs that need to run on the script (tentatively named `forgeScripts`). Then we have a very easy "pointer" for the MPS redeemers: the index of the MPS in `forgeScripts`.

**Comment by polinavino** [comment]
This is settled (as currently in the spec)
