### ISSUE TITLE
Shelley previous hash (in block header)

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#1266]
For use in the hard fork combinator, the we need to change the prev hash so that it looks something like:

```
data PrevHash crypto
    -- | The first Shelley block 
    -- 
    -- For a Shelley only chain, the hash here would be the hash of the genesis config.
    -- For a Byron/Shelley chain, the hash here would be the hash of the final Byron block.
    Genesis !(HashHeader crypto)

   -- | Any subsequent block
  | Block !(HashHeader crypto)
```

see [consensus ticket #1175](https://github.com/input-output-hk/ouroboros-network/pull/1175)

**Comment by edsko** [comment]
On second (third? fourth?) thought, this is actually unnecessary. Consensus will anyway introduce a split between before-hard-fork blocks and after-hard-fork blocks, this is unavoidable. We were anyway planning to turn that into a 3-way split, where we explicitly mark the first hard-fork block as such. Since we will not instantiate consensus to Shelley, but rather to the hard fork combinator, introducing this 3-way split, there is no need to _also_ mark the first block Shelley side -- that would result in unnecessary double overhead.
