### ISSUE TITLE
Introducing multicurrency prior to Plutus

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1281]
The possibility of introducing multicurrency before full plutus would look roughly like:

- `forge` field in Tx added
- `Value` type in the UTxO (instead of the Ada-only Coin right now)
- `scriptsNeeded` function would include (in the set it produces of all the script hashes that must have the corresponding scripts run) the hashes of currency IDs in the forge field (and the transaction is obligated to carry all these)
- there must be a scripting language fully specified by the ledger rules (similar to how multisig works) that can be used as the monetary policy for the forged tokens
- no serious other major rule changes

Does this sound feasible/reasonable?
Would it be possible to make this work by using only multisig scripts?

More extensive multisig functionality can of course be added when full plutus is integrated, but would it be of any use or benefit to have this intermediate step?

**Comment by polinavino** [comment]
@michaelpj 's summary:

- Multicurrency with multisig MPSs makes sense as a development stage, but isn't that useful from a business perspective, so not worth releasing separately
- Multicurrency with a special MPS language might be more useful from a business perspective, but shackles us to another legacy language forever, so seems unappealing
- Multicurrency with Plutus handles all the usecases but can't be released before Goguen

**Comment by michaelpj** [comment]
From some discussion on Slack with Duncan and Manuel.

On an MPS language:
- It won't be able to do NFTs, since that requires global state (and state machines)
- It might be able to do staged release via issuing tranche tokens up front and later converting them
- We would need to be able to do at least the following:
    - Spend a specific output (replay protection)
    - Spend/forge/destroy/output to an address some particular `Value`
    - Get own hash (hence own currency ID)
    - Get/work with the transaction validity interval
    - Numeric functions
    - Boolean functions
- We could implement it with a Plutus interpreter (as for Marlowe) for development and testing purposes.

On the strategy:
- Doing a version with just multicurrency and multisig scripts for the MPSs seems like a good development strategy.
    - Lets us test a lot of things in a simpler scenario, without requiring Plutus integration
    - However, it has little business value (multisig is too weak) so probably not worth actually releasing it
    - Michael: some things that people claim they want to do with multicurrency would work with multisig only, although maybe those are bad ideas (e.g. gaming examples, service tokens)
- Launching with a specialized MPS language might be worth it
    - Duncan: if we can cover >80% of MPSs
    - Michael: can't obviate need for Plutus as a MPS lang, some MPSs are complex
- A specialized MPS language might be better fitted to the token builder UI anyway.
- The ecosystem forcing function would be useful for getting people to make the requisite changes for multicurrency. In particular:
    - Wallets need UI work to display them
    - Other services need plumbing work (explorer, wallet backend, etc.)
    - Exchanges need to adapt (!)
- Unclear if we would get enough ecosystem forcing from multicurrency-with-multisig,  or whether we need multicurrency-with-MPS-language

**Comment by michaelpj** [comment]
I realised that I was overly pessimistic about NFTs:
- If you only ever do a single forging transaction (e.g. spend one specific output), then you have no risk of re-forging things.
- If you want to forge NFTs in several tranches, there are tricks you can do, e.g. "sharding" the NFTs:
    - Do a one-off issuance of tranche tokens, each of which "owns" a shard of the token names (e.g. all those beginning with "A")
    - Allow consuming a tranche token to produce a tranche of NFTs in that shard
    - Each shard gets issued only once, script can assure no overlap in the issuing, so we end up with global uniqueness

**Comment by j-mueller** [comment]
> We would need to be able to do at least the following:

I'd add the following point. I think it was implied but it seems like an important bit.

* Work with the token name - basic string operations like `append`, `contains`, string literals. If there are no data values then the token name will probably be used to store some data, so we should try to make it easy to get that data out. (You could actually fit a state machine in there, by destroying the token with the old state and forging a token with the new state)

Re. the question of how many use cases a specialised MPS language would cover:

* Use cases themselves are not well defined. We would certainly be able to do _some form_ of tokenised assets, KYC, whatever, with a specialised MPS language. But chances are that someone has a specific token/KYC use case that can only be done in full Plutus, and the technical details that make the difference are not easy to explain. So if we are talking about specific use cases at the very least we need very clear definitions of what they mean.
* The number of use cases isn't a measure that reflects the business goals very well. An alternative measure would be the market capitalisation of Ethereum contracts that can be expressed in the MPS language. Or, even better than market cap: operating cost, if we can undercut. Or, instead of looking at all/top-n Ethereum contracts we could look at the use cases that our launch partners have and try to cover a subset of them. Or we could say, what matters most is how we communicate it, and then any MPS language is good enough as long as it can produce tokens. 
* Whatever MPS language we choose, the tokens that it produces will be re-usable in all future Plutus contracts. So if someone wants to build a fancy dapp on Plutus, they could finance it right away by selling the tokens, and by the time they have finished building the app, full Plutus will have been released already.

So to summarise I think the expressivity of the MPS language is hard to gauge, but it isn't that important, as long as it is clear that the MPS language is only a stepping stone towards the full release of Plutus.

> Multicurrency with a special MPS language (...) shackles us to another legacy language forever

Yeah I think that's a very important issue, esp. as that language is going to compete with Plutus for the scripts that can be expressed in it. Pricing the MPS scripts seems quite tricky to me: If they are too cheap then the MPS language is always going to be used where possible and people will try to get it to do things that it wasn't designed for. Ideally it would be more expensive than a comparable script in Plutus, but then it might be too expensive compared to other solutions which is going to hinder adoption. Or maybe we could say the prices are artificially low during the "beta period" (until Goguen release) so that nobody is surprised when they go up a little.

It would be great if we could use the actual Plutus interpreter for evaluating the MPS scripts on the ledger, so that the language would be like another Marlowe.

**Comment by michaelpj** [comment]
> You could actually fit a state machine in there, by destroying the token with the old state and forging a token with the new state

> Pricing the MPS scripts seems quite tricky to me: If they are too cheap then the MPS language is always going to be used where possible and people will try to get it to do things that it wasn't designed for.

What a horrifying idea. I think this is very important: we must keep the MPS language weak enough to not express more sophisticated programs *or* we need to be very careful that it's more expensive than Plutus.

What we really don't want is a situation where "best practice" for minimizing costs is to do a horrifying abuse of the MPS langugage to implement some state machines, or similar.

**Comment by polinavino** [comment]
It will definitely be really tricky to figure out any strategy for using strictly Plutus for MPS, including for existing MC tokens, when Goguen comes out. 

It might be work have a MC native language, with one of the constructors being something like "run this MC script OR run this Plutus script", which before Goguen will always evaluate to `False`

**Comment by michaelpj** [comment]
We previously discussed how much would be possible if we *just* used the multisig language for MPSs. I've previously argued that many kinds of "central authority tokens" (where one party is entirely in control of creating and destroying them, often to reflect off-chain state), such as game item tokens, don't make a lot of business sense, and would be better tracked in an off-chain database. Manuel argued that this damns more-or-less everything that you can do with multisig-only MPSs.

However, this is not quite true. The reason gaming tokens don't make sense is that you mostly only care about ownership. You're unlikely to want to make a fancy derivative contract with them. But this is not true for e.g. stablecoins, some varieties of which are precisely this sort of "central authority token". People might *well* want to do a fancy derivative contract with tokens representing USD.

So I think that's *a* usecase for multisig-only MPSs, and it's a fairly big one. Perhaps not big enough alone to justify launching multicurrency with multisig-only MPSs, but worth considering.

**Comment by polinavino** [comment]
Using an MPS language that combines MSig and a clause that limits the total (ever in existence, or at a given slot) number of each kind of token of a currency would already make this MPS much more useful (and is super easy and safe)

**Comment by michaelpj** [comment]
> a clause that limits the total (ever in existence, or at a given slot) number of each kind of token of a currency

I think that's way out, that's global state, which we definitely don't want to just randomly introduce!

Managing the number of tokens in circulation is not trivial (without adding global state), and I think the best suggestion so far was something like tranche tokens.

**Comment by polinavino** [comment]
Ah! Right. Global state : (

**Comment by JaredCorduan** [comment]
we are doing this indeed :)
