### ISSUE TITLE
Optimize VRF validation and leader probability calculation

### ISSUE THREAD

**Issue by mgudemann** [input-output-hk/cardano-ledger-specs#317]
The VRF compares the result of a non-integral calculation to a threshold value. The goal of this issue is to optimize this, as VRF calculation is done quite often. It might be possible to pre-compute parts of the required calculation and / or terminate at an early iteration.

**Comment by vantuz-subhuman** [comment]
Sorry for using this issue for this question, but wouldn't want to create a new one for something this simple.

I might have missed it, but is there already a known spec for the exact VRF function to be used in Praos? What documentation is used to implement VRF in this repo?

Thank you!

**Comment by JaredCorduan** [comment]
> I might have missed it, but is there already a known spec for the exact VRF function to be used in Praos? What documentation is used to implement VRF in this repo?

@mgudemann is actually referring to some of the calculations used in the new `VRF` section of the spec, not the actual crypto (which is abstract in the spec). in particular, he's looking at how we'll compute `1-(1-f)^s` (which is tricky since it's a real valued calculation).

There is an appendix in the [Praos paper](https://eprint.iacr.org/2017/573.pdf) which talks about implementing a VRF function, but I'm not sure how closely that matches what we will actually go with. I can look into this for you. thanks!

**Comment by vantuz-subhuman** [comment]
> There is an appendix in the [Praos paper](https://eprint.iacr.org/2017/573.pdf) which talks about implementing a VRF function, but I'm not sure how closely that matches what we will actually go with. I can look into this for you. thanks!

Oh yeah, I've seen the formal definitions they give in that appendix, but yes - it doesn't seem to provide any details on how that magic works with VRF being able to calculate the leader schedule, but keep it mostly secret for the local node )

After being described in the Praos paper that idea of a VRF became very popular in the community and interested a lot of people, and I only were able to explain main points on how the function would allow on one side to basically use the snapshot, the current slot, and your private key to construct a proof that you are actually the correct leader, and on another side to use the equal snapshot, the same slot, and your public key, to verify this constructed proof. And this part sounds fairly easy to imagine, even without knowing the actual used crypto-primitives. But the main part that people are wondering and I can't explain due to very limited knowledge is how the random selection is performed in such a way that does not expose the schedule to the node executing the VRF 😄 So I'm just trying to monitor repos for any new info available about that part.

The only way I can imagine it - is if part of private keys themselves are numerically used for the chance calculation, in which case VRF just calculates the chance of this **lexicographical** private key to be a leader for the particular slot. But because chance of each key to be selected supposed to be weighted according to stake distribution (by public keys) - I can only assume that VRF would need to consider some "regions" of the whole PK lexicographical field as weighted by some stake, and then the whole field to also be somehow spread across the number of slots in the epoch. Which would then allow to calculate if some specific PK lexicographically is in the region of stake and in the region of epoch to have a good enough chance to be a leader. Which at the same time sounds like absolute madness to me, but I can't imagine it to work any other way so far 😭 

If there's any public info that can be found - will extremely appreciate it! 🙌

**Comment by JaredCorduan** [comment]
ah, gotcha!  I think maybe I can help then (but apologies if I'm attempting to explain something you already understand :smile:  ). This all relates to the new section that I am currently adding to the shellley ledger spec (what is currently section 11 in master, the "Blockchain layer"). It's a WIP.  Figure 53 (VRF rules) is the most relevant here.

All you need to know about the VRF is that you can give it a seed (which will be publicly known for us, one for each slot) and a private key, and it pops out a value between 0 and 1 (or more generally, any type T, but for leader election it's a number in this interval) and a proof. And with just the seed, the corresponding pubkey, the value, and the proof, anyone can check that the owner of the private key did infact generate that value using the VRF.  and we just compare this value `l` to the relative stake (checking that `l < 1 - (1-f)^s`) to see if they key had the right to issue a block.  so without someone's private key, you do not know what their `l` will be for each slot in advance, but you can check them as they come in.

Did that help? Thanks for keeping folks informed!! :raised_hands:

**Comment by vantuz-subhuman** [comment]
> All you need to know about the VRF is that you can give it a seed (which will be publicly known for us, one for each slot) and a private key, and it pops out a value between 0 and 1 (or more generally, any type T, but for leader election it's a number in this interval) and a proof. And with just the seed, the corresponding pubkey, the value, and the proof, anyone can check that the owner of the private key did infact generate that value using the VRF. and we just compare this value `l` to the relative stake (checking that `l < 1 - (1-f)^s`) to see if they key had the right to issue a block. so without someone's private key, you do not know what their `l` will be for each slot in advance, but you can check them as they come in.

Yep, this is exactly the part I was able to explain so far 😄 Wonder where exactly the value between 0 and 1 comes from 😁

**Comment by JaredCorduan** [comment]
ah, gotcha :smile: I don't know the details on that yet.  yet!
