### ISSUE TITLE
Decision: Signatures from reward account key on stake pool registration certificates?

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-ledger-specs#384]
Currently, we do not require a signature from the key controlling the reward account when registering a stake pool.

As a result, someone could open a stake pool, and send the rewards for the operator to a third party, without the third party consenting to this.

If this is an issue, we could prevent this by requiring a signature by the key of the reward account. This would make the certificate slightly larger, and slightly increase the effort required to set up a charity pool.

**Comment by vantuz-subhuman** [comment]
One of the points of making reward accounts a separate parameter, as discussed, was so that people can open "charity" pools and specify some known public reward account key as reward target, so delegates can see and verify that rewards are going to the key owner automatically, so there's no need to believe pool owner.

Requiring reward key signature might complicate cases **like** this one. Not telling it should not be done, but just providing additional input and context for the decision.

**Comment by kantp** [comment]
We discussed this at the delegation session at the company meeting last week; the consensus was that there is no need to change this.

In particular, we should not be concerned about people sending rewards to someone without them consenting to it, since ordinary transactions cannot be rejected by the receiver either.
