### ISSUE TITLE
Shelley max transaction size

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#442]
There is a max transaction size in the Byron rules. Currently in the Shelley rules, there is a max block body size, but no max transaction size. Confirm whether on not such a max transaction size is wanted for Shelley.

**Comment by erikd** [comment]
There very definitely should be a maximum size.

**Comment by vantuz-subhuman** [comment]
Also will be awesome if it's not 8 kb

**Comment by erikd** [comment]
@vantuz-subhuman Why is 8k not enough? What would you suggest?

**Comment by vantuz-subhuman** [comment]
> Why is 8k not enough?

@erikd, initially the limit size was 64 kb and was reduced to 8 kb as a matter to solve the giant addresses problem when hackers figured they could put 60kb of random meta-data into addresses (when we had pictures in addresses).

Now that limit is 8 kb people sometimes get their funds locked in Daedalus with no way to send them without using API, because they have large number of UTxO on the same address and cardano-sl defaults to archaic spec that says that UTxO should not be partially spent from 1 address, meaning that either no UTxO is used from a specific address, or all of them. If people have around 80 or so UTxO on the same address - their transaction get so large that it doesn't fit in 8 kb limit. Which only could be changed by manually sending a request and setting an API flag that changes input-selection to "network-friendly" so it starts to minimise used inputs.

8 kb limit was a quick hack to solve an unrelated problem with addresses which caused a ton of pain to Daedalus users and community tech-support (since official tech-support could not even understand the problem and just told all users to download latest version, which solved nothing), and I bet to "enterprise" parties, like exchanges, who like to minimise number of transactions by applying more inputs/outputs. There's absolutely no reason to have it, because even in cases where people are able to work around it it only forces them to use more smaller transactions, which costs them more coins, and actually makes them waist MORE on-chain space, because each transaction also adds some meta-data and wrappers, so just using more inputs/outputs would save space in the long run.

I see no reason to make tx-size limit lower than initial 64 kb, if not larger.
