### ISSUE TITLE
Document and specify the process for doing the OBFT hard fork in cardano-sl

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#462]
- Check how the transition will take place:
   - bumping the major protocol version?
   - using the epoch stake unlock parameter?

We need to make sure that:
- our current specification matches the actual mechanism in `cardano-sl`
- our implementation can cope with it (might need to make an issue in `cardano-ledger`).
- the details should be written down somewhere (Byron spec or some other document).

**Comment by mhuesch** [comment]
I _think_ this issue might have been resolved from discussion in Slack.

The hard fork process was documented in the (private) core-team-notes repo here:
https://github.com/input-output-hk/core-team-notes/blob/master/hard-fork-mechanism-walkthrough.md
https://github.com/input-output-hk/core-team-notes/pull/18/files?short_path=f572f41#diff-f572f417b8e2dccdd60e67cc008e64be

The above documents are for a "dev" cluster, and there is a slight difference for a mainnet/staging cluster, due to the genesis block being fixed and unchangeable, in contrast to dev, which doesn't have a fixed genesis configuration.

**Comment by dnadales** [comment]
> I think this issue might have been resolved from discussion in Slack.

:heavy_check_mark: Closing now, since it has no impact in our specs...
