### ISSUE TITLE
FADS STS - further align with formal spec

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#680]
Make "OR fads == EMPTY" in the exec. spec more explicit, as in the formal spec:

![Screenshot6](https://user-images.githubusercontent.com/8812/62035975-2b1bfd00-b1f1-11e9-907e-a738968dff4b.png)

**Comment by csoroz** [comment]
In the formal spec, is it necessary to use the AND operator in the precondition? Rule (34) does something similar without using it. In fact, those rules seem to be related. Would be clearer if both use the same notation IMHO. I find the notation in rule (34) simpler.

**Comment by dnadales** [comment]
> In the formal spec, is it necessary to use the AND operator in the precondition?

I think it is: the top level operator of the premise is an `OR`, so we need the parenthesis and the `AND` symbol to achieve this. In rule `(34)` there's no `OR` operator, and since all the conditions in the premises are interpreted as the conjunction of them, we don't need to use the operator.

I wouldn't know how one could express `(33)` in a more elegant way, but ideas are welcome ;)

**Comment by csoroz** [comment]
OK, I was missing this notational convention that resembles Haskell’s pattern matching:
![B5AE0323-174B-4057-9531-CE403E9BBAEB](https://user-images.githubusercontent.com/3624828/63560001-89b86a80-c554-11e9-9fab-6c885b9cb614.jpeg)
Makes sense, although still seems unusual that a binding can appear as predicate inside a logical expression!
I don’t know if I can come up with something better than the current code:
https://github.com/input-output-hk/cardano-ledger-specs/blob/458324852cd1b68bfff35f30ee3a1298b736f106/byron/ledger/executable-spec/src/Ledger/Update.hs#L662
Maybe something like:
```
case fads of
  ((_, (pvc, _)) : _ ) | pvc < bv -> (sn, (bv, ppsc)) : fads
  []                              -> (sn, (bv, ppsc)) : fads
  _ -> fads
```

**Comment by dnadales** [comment]
> unusual that a binding can appear as predicate inside a logical expression!

I agree, and I guess we're feeling this pain somehow since as you pointed out, there isn't a direct translation into Haskell (the closest one I can think of being a case statement).

> Maybe something like:

I guess to do this we'd have to introduce the notion of case statements in the formalism, which might complicate things a bit further.

**Comment by csoroz** [comment]
Maybe you misunderstood my comment or wasn’t very clear? The code at the end is not a proposal for change in the formalism, it is for the Haskell implementation in the exec spec. But I suppose it is not enough aligned with the formal spec to fix the issue...

**Comment by dnadales** [comment]
> The code at the end is not a proposal for change in the formalism, it is for the Haskell implementation in the exec spec. But I suppose it is not enough aligned with the formal spec to fix the issue...

Oh, I see. Well I guess your proposal is also fine. Maybe using the singleton `[(sn, (bv, ppsc))]` instead of `(sn, (bv, ppsc)) : fads` makes things even clearer. 

The only objection has to do with style: we try to minimize diffs when submitting PR's, so I wouldn't align the arrows.

**Comment by dnadales** [comment]
>  Maybe using the singleton [(sn, (bv, ppsc))] instead of (sn, (bv, ppsc)) : fads makes things even clearer.

Oh, but then this will place the executable spec further from the formal spec. So ignore the previous comment.
