### ISSUE TITLE
Sync executable with formal spec - LEDGER STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#736]
<img width="874" alt="Screenshot_FIG32" src="https://user-images.githubusercontent.com/8812/62697688-8b722200-b9db-11e9-8a0e-57e1a3a8a0e1.png">

Order of STS application differs:

* in the **formal spec** LEDGER rule, we apply the DELEGS rule first and use the transformed delegation state as part of the environment for applying the UTXOW rule
* in the **exec. spec**, the UTXOW rule is applied first and uses the delegation state prior to the DELEGS rule being applied.

**Comment by mgudemann** [comment]
please see here https://github.com/input-output-hk/cardano-ledger-specs/pull/704/files
the sequence has been changed in the formal spec. The reason was that else we first apply the certificates, e.g., change the set of stake pools, and then the `consumed` value was calculated via checking which certificates get applied independently. This lead to the situation that pool deposits were not paid.
Now the formal spec does what the exec spec did before, first collect the necessary values and then apply the certificates.

**Comment by uroboros** [comment]
👍  I'll close this
