### ISSUE TITLE
define valid initial Shelley ledger states

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#840]
We should explicitly define the valid initial Shelley ledger states. In particular, for what Byron states `B` does `toShelley B` give a valid initial state?

**Comment by kevinhammond** [comment]
This will allow us to ensure a smooth migration since the Shelley ledger will not be starting from absolute zero.  The state that we start in should ideally be one that can be reached by following valid state transitions from absolute zero, but must certainly meet any conditions that are necessary to ensure invariants for future transitions (including e.g. consistency/preservation of ada).
