### ISSUE TITLE
Trace generator for LEDGER STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#844]
To generate DCerts, the appropriate level in the STS hierarchy is LEDGER, where we have sufficient context (utxo) to generate meaningful certificates. 

This issue is to write a Tx/DCerts generator for the LEDGER STS, and using the existing tx/utxo generators as scaffolding and focus on DCert generation.

**Comment by kevinhammond** [comment]
Let me know if I can help with this in some way (once I've chewed off the other things I'm looking at).  I have some experience with generators of various kinds.

**Comment by uroboros** [comment]
thanks @kevinhammond that would be great  - I'll add you as a reviewer to the PR for this issue, in case you have time to look at it

**Comment by kevinhammond** [comment]
Sure!  Just let me know when you're looking at progressing it.

> On 6 Sep 2019, at 14:30, ryan lemmer <notifications@github.com> wrote:
> 
> thanks @kevinhammond that would be great - I'll add you as a reviewer to the PR for this issue, in case you have time to look at it
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Best Wishes,
Kevin

--------

E: kevinhammond.net, W: http://www.kevinhammond.net	

This email reflects the opinions of the individual concerned, may contain confidential or copyright information that should not be copied or distributed without permission, may be of a private or personal nature unless explicitly indicated otherwise, and should not under any circumstances be taken as an official statement of policy or procedure.
