### ISSUE TITLE
Review and analyse the shrinking problem

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#938]
Gather examples for the shrinking that we are having and propose a strategy going forward, to either switch to Quickcheck from Hedgehog or invest in more efficient Hedgehog generators.

**Comment by mgajda** [comment]
@uroboros reported that there are often issues with efficiency of shrinking.
I understand these are related to #938, #708, #684 (epic).

He suggested that I read Edsko's post https://www.well-typed.com/blog/2019/05/integrated-shrinking/, and we organize meeting with @dnadales @uroboros @mgajda @kevinhammond @mhuesch on what are the current problems, and how to best address them.

**Comment by mgajda** [comment]
I looked at the shrinkers here:
* https://github.com/dnadales/sandbox/blob/c63956ad1c69c122fe897b0735f9553f85073d39/quickcheck-vs-hedgehog/test/large-shrink-space/MagicLengthBlockChain.hs
* https://github.com/input-output-hk/decentralized-software-updates/commit/9cdcfee25d5d6b8242f40aa3122d356c5387184c
* https://github.com/input-output-hk/decentralized-software-updates/commit/9cdcfee25d5d6b8242f40aa3122d356c5387184c
* https://github.com/input-output-hk/cardano-ledger-specs/pull/963

In my perception, this is an issue of defining and benchmarking shrinkers, which should be done in advance of using them in the tests. So it is not so much QuickCheck vs Hedgehog, but good vs bad shrinkers.

Here are my proposals:
1. I can easily visualize shrink tree breadth with QuickCheck, how to do it with Hedgehog?
import Test.Quickcheck.Arbitrary

main = print $ length $ shrinkList shrink [1..100]
2. I thought it would be best to benchmark all shrinkers and generators, instead of waiting for them to fail.
In QuickCheck we could try like this:
```
print (shrinkDepth shrink sampleData
         ,shrinkBreadth shrink sampleData)

shrinkBreadth = length . shrink
shrinkDepth = length . iterate (concatMap shrink) . ([]:)
```
How to formulate similar quantities in Hedgehog?

3. It seems more difficult to understand explicit shrinkers defined in Hedgehog (`runTreeT` and `bitraverse`) instead of Quickcheck.

It stills seems that we miss some simple abstraction, since all these dig deep into implementation details (using explicit shrink trees, `runTreeT`)
The main reason why QuickCheck was faster was that:
• to make sure we shrink by halves if possible (to reduce tree depth)
• to make sure we interleave shrinks between different substructures
It looks like we should use generic Applicative-like shrinking merger `<$>` and `<*>`, and then postprocess the arguments by _fixing_ them.

**Comment by mgajda** [comment]
The way forward seems:
1. I will review the shrinker that @uroboros proposed to write for `genTx` in Shelley.
2. I will finish PR with my comments on `genTxFromUtxo` in Byron.
3. I would implement these measures both in QuickCheck and Hedgehog so we have the tools to assess shrinkers in detail.

**Comment by mhuesch** [comment]
Another example of a poor shrink: https://github.com/input-output-hk/cardano-ledger-specs/commit/024822853e0ec7b1257dde9dc84f4d64c6ccb616

```$ cabal v2-test delegation-test```

**Comment by dnadales** [comment]
Please, also bear in mind that https://github.com/hedgehogqa/haskell-hedgehog/issues/333
