### ISSUE TITLE
Interfacing Consensus with Ledger

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-ledger-specs#981]
We need to specify the interface between the consensus and ledger layers.  We have had a preliminary discussion about this.  I propose that we work on this in the new branch consensus-ledger-interface (consensus.tex), also integrating work from the Isabelle proof/implementation.

The consensus layer is designed to call the ledger top-level function as a pure function that will return a new block.  It will pass the ledger some input parameters relating to the Genesis block, the current slot etc; other than the new block, no output parameters for the ledger have yet been defined, however.  The consensus implementation has been parameterised using type classes so that it can accept  either a Byron or Shelley ledger implementation.  The type class restricts the properties that the ledger implementation must comply with, so allowing a "drop-in" implementation.  The consensus implementation works only at a single node as part of the full distributed consensus mechanism (Praos or Genesis).

The consensus layer assumes that the ledger will successfully produce a new block within the required time limits (20s for a complete slot) and does not consider any other extra-functional requirements (e.g. memory limits etc.).  It may be necessary to embed these elsewhere, or to extend the consensus layer so that it accounts for/recovers from any failures at this level.

**Comment by jeltsch** [comment]
> I propose that we work on this in the new branch `consensus-ledger-interface` (`consensus.tex`), also integrating work from the Isabelle proof/implementation.

While we are at it, I’d like to mention that @javierdiaz72 and I prefer to develop any Isabelle formalizations of ledger stuff in a separate repository, as this formalization work is a kind of separate effort (although clearly related to the work in `cardano-ledger-specs`) and we have a different workflow (for example, having milestones aligned with our bi-weekly project meetings).

By the way, it’s not even clear whether we’ll be permitted to work on these formalizations, since Chris hasn’t given any green light yet.

About the actual topic of this issue, I cannot really comment at this point, as my knowledge of Ouroboros is still quite limited. That said, I hope to be enlightened by you. 🙂 Also, @javierdiaz72 will spent considerable amounts of the next 2–3 weeks to get more into the details of Ouroboros and thus might have ideas to contribute here.

**Comment by nc6** [comment]
I'm developing an API for this (on the implementation side) in this branch: https://github.com/input-output-hk/cardano-ledger-specs/tree/nc/api

**Comment by jeltsch** [comment]
Hmm, I’m a bit confused: Recently, @edsko presented to us a Haskell API, which I thought was exactly about this interface. Could somebody perhaps clarify the situation?

**Comment by JaredCorduan** [comment]
I'm going to close this since @nc6 is working on it elsewhere.
